/** English UI strings (single-language build). */
import { TIERS } from './planets'

export const STR = {
  docTitle: 'Cosmic Merge',
  title1: 'Cosmic ',
  title2: 'Merge',
  score: 'SCORE',
  best: 'BEST',
  next: 'NEXT',
  bestMerge: 'TOP MERGE',
  evolution: 'EVOLUTION',
  starsTab: 'STARS',
  newStarBanner: (name: string) => `New star discovered: ${name}!`,
  goalBlackHole: 'Merge two Suns → a BLACK HOLE swallows everything and reveals a new star!',
  mute: 'Toggle sound',
  // 星座任務（招牌玩法）：頂端常駐目標 + 底部圖鑑分頁
  constellationLabel: 'CONSTELLATION',
  skyTab: 'SKY',
  constellationHint: (name: string) => `Chart the ${name} — merge planets to light its stars`,
  constellationDone: (name: string) => `${name} charted!`,
  constellationBonus: (n: number) => `+${n.toLocaleString('en-US')}`,
  skyMastered: 'Every constellation charted!',
  overTitle: 'The cosmos is full!',
  overScore: (s: number) => `You scored <strong>${s.toLocaleString('en-US')}</strong>`,
  overNewRecord: (p: string) => `New record! Highest merge: ${p}`,
  overNormal: (p: string, b: number) => `Highest merge: ${p} · Best: ${b}`,
  restart: 'Play Again',
  submitScore: 'Submit to Leaderboard',
  submitScoreDone: 'Submitted!',
  share: 'Share Score',
  shareDone: 'Card saved',
  leaderboard: 'TOP SCORES',
  globalLeaderboard: 'GLOBAL TOP SCORES',
  yourBest: 'YOUR BEST RUNS',
  bestNow: 'NOW',
  offlineLeaderboard: 'OFFLINE · YOUR SCORES',
  noScores: 'No scores yet — set the first record!',
  rankGlobal: (rank: number) => `Global rank #${rank}`,
  rankLocal: (rank: number) => `Your rank #${rank}`,
  rankGap: (gap: number) => `just ${gap.toLocaleString('en-US')} more to pass the one above!`,
  rankTop: "You're #1 in the world!",
  rankTopLocal: 'Top of your board!',
  namePlaceholder: 'Your name',
  // 每日連續登入獎勵彈窗
  dailyStreak: (n: number) => `Day ${n} streak`,
  dailyReward: (n: number) => `+${n} Hammer${n === 1 ? '' : 's'}`,
  dailyMilestone: 'Milestone bonus!',
  dailyClaim: 'Claim reward',
  dailyClaimed: (n: number) => `Daily reward: +${n}`,
  // 續玩（獎勵廣告）按鈕的各種狀態：清楚說明「要看廣告、能續玩、會清掉頂端」
  reviveMain: 'Continue Playing',
  reviveSub: 'Watch a short ad · clears the top',
  reviveSubLeft: (n: number) => `Watch a short ad · ${n} more ${n === 1 ? 'time' : 'times'}`,
  reviveLoading: 'Loading ad…',
  reviveLoadingSub: 'hang tight',
  reviveRetry: 'No ad available',
  reviveRetrySub: 'tap to try again',
  reviveDone: 'Second chance! Top cleared',
  hammer: 'Hammer (smash one planet)',
  hammerHint: 'Tap a planet to smash it (tap empty space to cancel)',
  hammerHintMini: '?',
  hammerAdPrompt: 'Watch a short ad for a hammer — tap again',
  tutorial: 'Drag to aim · release to drop<br>Matching planets merge!',
}

export function planetName(tier: number): string {
  return TIERS[tier].name
}
